### ISSUE TITLE
Patch breaks alloy smelter

### ISSUE THREAD

**Issue by Zemogiter** [TheOriginalArgon/Expanded-Materials-Metals#4]
Hello. Ive made a patch file that adds [Industral Revoultion's](https://steamcommunity.com/sharedfiles/filedetails/?id=2689358547) Coal into this mod's alloy smelter. The issue is this patch breaks the smelter - right clicking with pawn selected, no option to refuel is shown, only "cannot alloy limestone alloy smelter: need ingridients" despite both trin and copper being present in sufficient amounts on map. Both IR's coal and this mod's coal are present on map.
Patch below:
```
<Patch>
	<Operation Class="PatchOperationAdd">
	    <xpath>/Defs/ThingDef[defName = "VMEu_MetalSmelter"]/comps/li/fuelFilter/thingDefs/li</xpath>
	    <value>
            <li>IR_Coal</li>
	    </value>
	</Operation>
</Patch>
```
Log file:
https://gist.github.com/025e227200356b6fc39c69ef49524ecd

**Comment by TheOriginalArgon** [comment]
I think it doesn't work because you have to get rid of that last `/li` on the xpath

**Comment by Zemogiter** [comment]
Removed `/li`. Now it works thanks.
